import type { Property } from "../features/properties/types";

export const mockProperties: Property[] = [
  {
    id: "1",
    name: "Marina Tower Unit 4B",
    location: "Dubai Marina",
    pricePerToken: 500,
    totalSupply: 1000,
    availableTokens: 180,
    yieldPercent: 7.2,
  },
  {
    id: "2",
    name: "Downtown Loft 12A",
    location: "Downtown Dubai",
    pricePerToken: 750,
    totalSupply: 500,
    availableTokens: 498,
    yieldPercent: 6.1,
  },
  {
    id: "3",
    name: "JVC Studio Block C",
    location: "Jumeirah Village Circle",
    pricePerToken: 250,
    totalSupply: 2000,
    availableTokens: 12,
    yieldPercent: 8.4,
  },
  {
    id: "4",
    name: "Palm Villa Estate",
    location: "Palm Jumeirah",
    pricePerToken: 1250,
    totalSupply: 100,
    availableTokens: 15,
    yieldPercent: 5.5,
  },
  {
    id: "5",
    name: "Business Bay Heights",
    location: "Business Bay",
    pricePerToken: 400,
    totalSupply: 1500,
    availableTokens: 1100,
    yieldPercent: 6.8,
  },
  {
    id: "6",
    name: "DIFC Luxury Suite",
    location: "DIFC",
    pricePerToken: 850,
    totalSupply: 800,
    availableTokens: 0,
    yieldPercent: 5.9,
  },
  {
    id: "7",
    name: "Dubai Hills Mansion",
    location: "Dubai Hills Estate",
    pricePerToken: 2000,
    totalSupply: 50,
    availableTokens: 4,
    yieldPercent: 4.8,
  },
  {
    id: "8",
    name: "Creek Harbour View",
    location: "Dubai Creek Harbour",
    pricePerToken: 350,
    totalSupply: 3000,
    availableTokens: 2450,
    yieldPercent: 7.5,
  },
];
